services:
  db:
    image: mysql:8.0.38
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["go", "run", "main.go"]
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

