services:
  db:
    build: ./database
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/config/my.cnf:/etc/mysql/conf.d/my.cnf
      # 起動時にのCSVファイルをインポートする場合は以下のように指定する
      # - ./database/data.csv:/docker-entrypoint-initdb.d/data.csv
    entrypoint: /bin/bash -c "chmod 644 /etc/mysql/conf.d/my.cnf && chown mysql:mysql /etc/mysql/conf.d/my.cnf && docker-entrypoint.sh mysqld"
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["go", "run", "main.go"]
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:

